# Root directory to locate the content
# Default is the root directory of the repository.
root: ./Document

# Files to use as SUMMARY/README.
# (Relative to <root> directory)
structure:
  readme: Foreword.md
  summary: SUMMARY.md

# Redirect urls to specific files (relative to the <root> directory)
redirects:
  previous/page: new-folder/page.md
